import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Footer } from '../components/footer'
import { Nav } from '../components/Nav'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Final Proyect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <header>
          <Nav   />
        </header>

        <main className={styles.main}>
          <div className={styles.main_title}>
            <h1 className={styles.title}>
              Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>
          </div>
          <div className="input-wrapper">
            <span    aria-label="Ask us anything"></span>
            <span className="placeholder"></span>
          </div>
        </main>
      </div>



      {/* <footer className={styles.footer}> */}
        <Footer />
      {/* </footer> */}
    </div>
  )
}

export default Home
